# Multipart Config
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# AWS Account Config
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    stack:
      auto: false